[experimental]
lsp = true

[formatting]
line_length = 79

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[keymap]
preset = "vim"

[keymap.overrides]
"cell.createAbove" = "Ctrl-Shift-o"
"cell.createBelow" = "Ctrl-o"
"markdown.bold" = "Ctrl-b"
"markdown.italic" = "Ctrl-i"
"cell.splitCell" = "Ctrl-x"
"global.toggleLanguage" = "Cmd-m"
"cell.focusUp" = "arrowup"
"cell.focusDown" = "arrowdown"
"cell.run" = "Shift-enter"
"cell.runAndNewBelow" = "Cmd-enter"
"cell.moveUp" = "Cmd-Shift-arrowup"
"cell.moveDown" = "Cmd-Shift-arrowdown"
"cell.moveLeft" = "Cmd-Shift-arrowleft"
"cell.moveRight" = "Cmd-Shift-arrowright"
"cell.sendToTop" = "Cmd-g"
"cell.sendToBottom" = "Cmd-Shift-g"
"cell.addColumnBreakpoint" = "Cmd-Shift-b"
"global.formatAll" = "Cmd-Ctrl-Shift-f"
"markdown.link" = "Ctrl-w"
"cell.delete" = "Cmd-backspace"
"cell.aiCompletion" = "Cmd-Ctrl-Shift-a"
"cell.signatureHelp" = "Shift-Space"
"cell.format" = "Cmd-Shift-f"
"cell.goToDefinition" = "Ctrl-d"
"global.toggleTerminal" = "Ctrl-t"

[package_management]
manager = "pip"

[snippets]
custom_paths = []
include_default_snippets = true

[server]
follow_symlink = false
browser = "default"

[runtime]
reactive_tests = true
watcher_on_save = "lazy"
auto_instantiate = false
on_cell_change = "lazy"
std_stream_max_bytes = 1000000
auto_reload = "off"
output_max_bytes = 8000000

[display]
dataframes = "rich"
theme = "light"
cell_output = "above"
default_table_page_size = 8
code_editor_font_size = 12
default_width = "medium"

[completion]
activate_on_typing = false
copilot = false

[ai]
rules = ""
[ai.anthropic]

[ai.google]

[ai.open_ai]

[language_servers.pylsp]
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_pylint = false
enable_flake8 = false
enable_pyflakes = false
enable_mypy = true

[diagnostics]
enabled = false
